[debug]
verbose = false

[model]
model_path = "../models/phi-4-Q6_K.gguf"
num_max_content_tokens = 16384
num_gpu_layers = 41
num_buffer_size = 1
prompt_without_rag = """<|im_start|>system<|im_sep|>You are an anomaly log detector. Please analyze logs according to the following refined criteria:

1. Log Level Filtering:
  - INFO level logs or logs with "debug" marked are normal.
  - WARNING/ERROR/FATAL level logs maybe abnormal. You should analyze the log according to the third part.

2. Special cases:
  **The Cases Below should not be detected to anomaly log.**
  - RAS APP FATAL ciod: Error loading PATH: invalid or missing program image, Permission denied.
  - RAS APP FATAL ciod: Error loading PATH: invalid or missing program image, No such file or directory
  - RAS APP FATAL ciod: Error loading PATH: invalid or missing program image, Exec format error
  - RAS APP FATAL ciod: LOGIN chdir(PATH or pwd) failed: No such file or directory
  - RAS KERNEL INFO ciod: Missing or invalid fields on line 1 of node map file PATH
  - RAS MMCS ERROR idoproxydb hit ASSERT condition: ASSERT expression=0 Source file=idotransportmgr.cpp Source line=1043 Function=int IdoTransportMgr::SendPacket(IdoUdpMgr*, BglCtlPavTrace*)

3. Module Context Analysis:
  **Anomaly Log Must Satisfy One Of The Following Classes:**
  1. Application Errors(RAS APP FATAL):
    - Application Child Process Error: There is no child processes when creating node map.
    - Application I/O Operation Error: Input/output error in chdir.
    - Application Stream Read Error: Failed to read message prefix.
    - Application Connection Reset Error: Connection reset by peer when reading message prefix.
    - Application Link Severance Error: Link has been severed when reading message prefix.
    - Application Connection Timeout Error: Connection timed out when reading message prefix.
  2. Kernel Errors(RAS KERNEL FATAL):
    - Kernel Data TLB Error: data TLB error interrupt.
    - Kernel Storage Error: data storage interrupt.
    - Kernel Filesystem Mount Error: Lustre mount FAILED.
    - Kernel Packet Reception Error: Error receiving packet on tree network, type mismatch.
    - Kernel Real-Time System Panic: rts panic.
    - Kernel Termination Error: Kernel terminated for some reason.

After completing the analysis, you only need to output Yes/No to indicate whether the log is abnormal. **DO NOT OUTPUT THE ANALYSIS.**<|im_end|><|im_start|>user<|im_sep|>New logs are as follows:
{log}<|im_end|><|im_start|>assistant<|im_sep|>"""
prompt_with_rag = """<|im_start|>system<|im_sep|>You are an anomaly log detector. Please analyze logs according to the following refined criteria:

1. Log Level Filtering:
  - INFO level logs or logs with "debug" marked are normal.
  - WARNING/ERROR/FATAL level logs maybe abnormal. You should analyze the log according to the third part.

2. Special cases:
  **The Cases Below should not be detected to anomaly log.**
  - RAS APP FATAL ciod: Error loading PATH: invalid or missing program image, Permission denied.
  - RAS APP FATAL ciod: Error loading PATH: invalid or missing program image, No such file or directory
  - RAS APP FATAL ciod: Error loading PATH: invalid or missing program image, Exec format error
  - RAS APP FATAL ciod: LOGIN chdir(PATH or pwd) failed: No such file or directory
  - RAS KERNEL INFO ciod: Missing or invalid fields on line 1 of node map file PATH
  - RAS MMCS ERROR idoproxydb hit ASSERT condition: ASSERT expression=0 Source file=idotransportmgr.cpp Source line=1043 Function=int IdoTransportMgr::SendPacket(IdoUdpMgr*, BglCtlPavTrace*)

3. Module Context Analysis:
  **Anomaly Log Must Satisfy One Of The Following Classes:**
  1. Application Errors(RAS APP FATAL):
    - Application Child Process Error: There is no child processes when creating node map.
    - Application I/O Operation Error: Input/output error in chdir.
    - Application Stream Read Error: Failed to read message prefix.
    - Application Connection Reset Error: Connection reset by peer when reading message prefix.
    - Application Link Severance Error: Link has been severed when reading message prefix.
    - Application Connection Timeout Error: Connection timed out when reading message prefix.
  2. Kernel Errors(RAS KERNEL FATAL):
    - Kernel Data TLB Error: data TLB error interrupt.
    - Kernel Storage Error: data storage interrupt.
    - Kernel Filesystem Mount Error: Lustre mount FAILED.
    - Kernel Packet Reception Error: Error receiving packet on tree network, type mismatch.
    - Kernel Real-Time System Panic: rts panic.
    - Kernel Termination Error: Kernel terminated for some reason.

After completing the analysis, you only need to output Yes/No to indicate whether the log is abnormal. **DO NOT OUTPUT THE ANALYSIS.**<|im_end|><|im_start|>user<|im_sep|>New logs are as follows:
{log}
You must refer to the following ground-truth information for judgment:
{db_response}<|im_end|><|im_start|>assistant<|im_sep|>"""

[rag]
chroma_db_dir = "chroma_db"
collection_name = "documents"

[dataset]
dataset_name = "BGL"
dataset_path = "../dataset/BGL/BGL_2k.log"
