[debug]
verbose = false

[model]
model_path = "../models/phi-4-Q6_K.gguf"
num_max_content_tokens = 8192
num_gpu_layers = 41
num_buffer_size = 1
prompt_without_rag = """<|im_start|>system<|im_sep|>You are an anomaly log detector. Please analyze logs according to the following refined criteria:

**Logs highly similar to the following template are considered anomalous logs.**
**You need to compare the logs as a whole, not just make judgments based on certain keywords.**
**Note: A new log is considered abnormal only when it almost completely matches one of the following templates. During the analysis, differences in certain numerical values between the new log and the template are allowed (for example, the difference between <c022fa29> and <c009d15> is acceptable), but differences in specific parts are absolutely not allowed (for example, the difference between <IP>:<Port> and <a specific name> is unacceptable).**
  - pbs_mom: Bad file descriptor (9) in wait_request, select failed
  - pbs_mom: task_check, cannot tm_reply to 70789.ladmin2 task 1
  - pbs_mom: im_eof, Premature end of message from addr <IP>:<Port>
  - pbs_mom: Unknown error 15009 (15009) in job_start_error from node <IP>:<Port>, 71910.ladmin2
  - pbs_mom: Unknown error 15009 (15009) in abort attempted 16 times. ignoring abort request from node <IP>:<Port>, 71897.ladmin2
  - pbs_mom: node_bailout, 72302.ladmin2 POLL failed from node ln111 3)
  - kernel: GM: firmware error-46:SRAM parity error on NIC
  - kernel: GM: LANai is not running. Allowing port=0 open for debugging

**If a highly similar template is not found above, then this log is normal.**

After completing the analysis, you only need to output Yes/No to indicate whether the log is abnormal. **DO NOT OUTPUT THE ANALYSIS.**<|im_end|><|im_start|>user<|im_sep|>New logs are as follows:
{log}<|im_end|><|im_start|>assistant<|im_sep|>"""
prompt_with_rag = """<|im_start|>system<|im_sep|>You are an anomaly log detector. Please analyze logs according to the following refined criteria:

**Logs highly similar to the following template are considered anomalous logs.**
**You need to compare the logs as a whole, not just make judgments based on certain keywords.**
**Note: A new log is considered abnormal only when it almost completely matches one of the following templates. During the analysis, differences in certain numerical values between the new log and the template are allowed (for example, the difference between <c022fa29> and <c009d15> is acceptable), but differences in specific parts are absolutely not allowed (for example, the difference between <IP>:<Port> and <a specific name> is unacceptable).**
  - pbs_mom: Bad file descriptor (9) in wait_request, select failed
  - pbs_mom: task_check, cannot tm_reply to 70789.ladmin2 task 1
  - pbs_mom: im_eof, Premature end of message from addr <IP>:<Port>
  - pbs_mom: Unknown error 15009 (15009) in job_start_error from node <IP>:<Port>, 71910.ladmin2
  - pbs_mom: Unknown error 15009 (15009) in abort attempted 16 times. ignoring abort request from node <IP>:<Port>, 71897.ladmin2
  - pbs_mom: node_bailout, 72302.ladmin2 POLL failed from node ln111 3)
  - kernel: GM: firmware error-46:SRAM parity error on NIC
  - kernel: GM: LANai is not running. Allowing port=0 open for debugging

**If a highly similar template is not found above, then this log is normal.**

After completing the analysis, you only need to output Yes/No to indicate whether the log is abnormal. **DO NOT OUTPUT THE ANALYSIS.**<|im_end|><|im_start|>user<|im_sep|>New logs are as follows:
{log}You could refer to the following ground-truth information for judgment:
{db_response}<|im_end|><|im_start|>assistant<|im_sep|>"""

[rag]
chroma_db_dir = "chroma_db"
collection_name = "documents"

[dataset]
dataset_name = "liberty2"
dataset_path = "../dataset/liberty2/liberty2-test.sub.key_event"