[debug]
verbose = true

[model]
model_path = "../models/Phi-3.5-mini-instruct-Q5_K_L.gguf"
num_max_content_tokens = 8192

num_gpu_layers = 33
num_buffer_size = 1

[rag]
chroma_db_dir = "chroma_db"
collection_name = "documents"

[dataset]
dataset_path = "../dataset/BGL/BGL_2k.log"
num_max_logs = 2000
