[debug]
verbose = true

[model]
model_path = "../../models/phi-4-Q6_K.gguf"
num_max_content_tokens = 8192
num_gpu_layers = 41
num_buffer_size = 1
prompt_without_rag = """<|im_start|>system<|im_sep|>You are an anomaly log detector. Please analyze logs according to the following refined criteria:

1. Special cases:
  **The Cases Below should not be detected to anomaly log**:

2. Module Context Analysis:
  **Anomaly Log Must Satisfy One Of The Following Situation:**
  1. **PBS Errors(Related to pbs_mom)**:
    - Bad file descriptor
    - Task check failed
    - Premature end of message
    - Unknown error 15009
    - Node bail out
  2. **GM Errors(Related to kernel with GM)**:
    - Firmware error
    - LANai is not running
  3. **Call Trace Action(Related to kernel with Call Trace)**
  4. **Network File System (NFS) Error(Related to netfs)**:
    - Mounting NFS filesystems failed
  5. **CCISS Error(Related to kernel with cciss):**:
    - sense key = 0x3
  6. **Auth Error(Related to su):**
    - Authentication failure

After completing the analysis, you only need to output Yes/No to indicate whether the log is abnormal. **DO NOT OUTPUT THE ANALYSIS.**<|im_end|><|im_start|>user<|im_sep|>New logs are as follows:
{log}<|im_end|><|im_start|>assistant<|im_sep|>"""
prompt_with_rag = """<|im_start|>system<|im_sep|>You are an anomaly log detector. Please analyze logs according to the following refined criteria:

1. Special cases:
  **The Cases Below should not be detected to anomaly log**:

2. Module Context Analysis:
  **Anomaly Log Must Satisfy One Of The Following Situation:**
  1. **PBS Errors(Related to pbs_mom)**:
    - Bad file descriptor
    - Task check failed
    - Premature end of message
    - Unknown error 15009
    - Node bail out
  2. **GM Errors(Related to kernel with GM)**:
    - Firmware error
    - LANai is not running
  3. **Call Trace Action(Related to kernel with Call Trace)**
  4. **Network File System (NFS) Error(Related to netfs)**:
    - Mounting NFS filesystems failed
  5. **CCISS Error(Related to kernel with cciss):**:
    - sense key = 0x3
  6. **Auth Error(Related to su):**
    - Authentication failure

After completing the analysis, you only need to output Yes/No to indicate whether the log is abnormal. **DO NOT OUTPUT THE ANALYSIS.**<|im_end|><|im_start|>user<|im_sep|>New logs are as follows:
{log}
You must refer to the following ground-truth information for judgment:
{db_response}<|im_end|><|im_start|>assistant<|im_sep|>"""

[rag]
chroma_db_dir = "chroma_db"
collection_name = "documents"

[dataset]
dataset_name = "Thunderbird"
dataset_path = "../../dataset/Thunderbird/Thunderbird.log.sub.key_event"
num_max_logs = 2205