[DEBUG]
VERBOSE = false

[MODEL]
MODEL_PATH = "../models/gemma-2-2b-it-Q6_K_L.gguf"
MAX_CONTENT_WINDOW_SIZE = 4096
# "You are an anomaly detector in a log system. You must choose one of words in 'yes'or 'no' as the result. The result should be surrounded by '##' tag. 'yes' means something failed or interrupted now. 'no' describes a process work normally or a normal state."
# "You are a log analyst. Analyze each log entry as normal (-) or abnormal (+). Output only `-` or `+`(without quote, space, colon or any other characters!). '+' means something failed or interrupted now. '-' describes a process work normally or a normal state. Base your decisions on common log analysis principles."
TEMPLATE = """
<start_of_turn>user
You are an anomaly detector in a log system. You must choose one of words in 'yes'or 'no' as the result. The result should be surrounded by '##' tag. 'yes' means something failed or interrupted now. 'no' describes a process work normally or a normal state.
{history}
**New logs are as follows:**
{log}
<end_of_turn>
<start_of_turn>model
"""
UPPER_CONTENT_WINDOW_SIZE = 2048
UPPER_OUTPUT_TOKEN_NUM = 1024
GPU_LAYER_NUM = 0
CONVERSATION_ROUND_KEEP_NUM = 1
BUFFER_SIZE = 1

[DATASET]
DATASET_PATH = "../dataset/BGL/BGL_2k.log"
MAX_LOG_NUM = 2000
